Support Pinning on section pages
parameter1/bizbash-media-websites pull request #217
Opened 2023-12-05 20:35 UTC by Shinsina

![Screenshot from 2023-12-05 14-33-18](https://github.com/parameter1/bizbash-media-websites/assets/46794001/b82ed62e-dd29-4d04-94a0-430b6e8b4673)
![Screenshot from 2023-12-05 14-33-23](https://github.com/parameter1/bizbash-media-websites/assets/46794001/654b63ab-12ae-4f62-ab8e-2f51253672d3)

2023-12-05 20:35 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add 'Pinning' to homepage for all sections](https://trello.com/c/kb70OSnn/226-add-pinning-to-homepage-for-all-sections)

2023-12-05 20:39 UTC, jwade1327 commented
@Shinsina They wanted this for the homepage. Under the section/block ‘Production & Strategy’ to be able to Pin a piece of content as the Hero-image/piece.

2023-12-05 20:40 UTC, jwade1327 requested changes
@Shinsina  They wanted this for the homepage. Under the section ‘Production & Strategy’ to be able to Pin a piece of content as the Hero-image/piece.

2023-12-06 13:16 UTC, jwade1327 approved these changes

2023-12-06 13:16 UTC, merged