Add Industry Buzz to hamburger menu.
parameter1/bizbash-media-websites pull request #29
Opened 2021-06-10 18:33 UTC by Shinsina

<img width="1920" alt="Screen Shot 2021-06-10 at 1 32 15 PM" src="https://user-images.githubusercontent.com/46794001/121578620-7bb92f80-c9f0-11eb-90a9-b62645fd1a2a.png">

2021-06-10 18:34 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [New Hamburger Menu item](https://trello.com/c/xhOmY4pj/58-new-hamburger-menu-item)

2021-06-14 18:40 UTC, solocommand requested changes

2021-06-14 18:40 UTC, solocommand commented on sites/bizbash.com/config/navigation.js
> +
```suggestion
const hamburgerMenu = [...topics, { href: '/industry-buzz', label: 'Industry Buzz' }];

```

There's no need to create a new variable and then modify it -- just define the variable using const and spread the existing items into it instead. Review the [prefer-const](https://eslint.org/docs/rules/prefer-const) ESLint rule for more info.

Ideally, this should be done on L128/L131, as there's no need to define this variable at all. It's only used once

2021-06-14 18:41 UTC, solocommand commented on sites/bizbash.com/config/navigation.js
> +
```js
// ...
    {
      label: 'Find Inspiration',
      items: [
        ...topics,
        { href: '/industry-buzz', label: 'Industry Buzz' }
      ],
    },
    {
      label: 'Other Resources',
// ...
```

2021-06-15 16:44 UTC, solocommand approved these changes

2021-06-15 16:44 UTC, merged