Styling updates
parameter1/bizbash-media-websites pull request #46
Opened 2021-07-28 16:44 UTC by Shinsina

<img width="1920" alt="Screen Shot 2021-07-28 at 11 03 52 AM" src="https://user-images.githubusercontent.com/46794001/127362913-4748eda9-2e76-4277-8252-758e793e25e8.png">
<img width="1920" alt="Screen Shot 2021-07-28 at 11 41 43 AM" src="https://user-images.githubusercontent.com/46794001/127362921-4f4ce3f4-7c7b-4b94-8468-fae24ac6f135.png">

2021-07-28 16:45 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [LOW URGENCY: Increase font size by 1 pt. in all header text](https://trello.com/c/cs3WiA5x/78-medium-urgency-increase-font-size-by-1-pt-in-all-header-text)

2021-07-28 16:45 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [LOW URGENCY: Increase line height on department headers below hero spot.](https://trello.com/c/0zsiCTNg/79-low-urgency-increase-line-height-on-department-headers-below-hero-spot)

2021-07-28 18:00 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [LOW URGENCY: Fix font bolding issue on Media Gallery.](https://trello.com/c/Dsb983HE/80-low-urgency-fix-font-bolding-issue-on-media-gallery)

2021-07-28 18:01 UTC, Shinsina commented
<img width="1920" alt="Screen Shot 2021-07-28 at 12 59 53 PM" src="https://user-images.githubusercontent.com/46794001/127373087-21394d55-84bc-4a08-8145-361deea9bf0f.png">

2021-07-29 12:57 UTC, zarathustra323 requested changes

2021-07-29 12:57 UTC, zarathustra323 commented on packages/global/scss/index.scss
> +    line-height: .5;
I would ask Ashton the actual line height value to use instead of "decrease by 1pt"

2021-07-29 12:59 UTC, zarathustra323 commented
For clarity, can you provide before and after screen shots and update your first PR comment to show them (as opposed to adding new comments).

2021-07-29 13:13 UTC, B77Mills commented on packages/global/scss/index.scss
> +    font-weight: 800;
800 is not a supported font weight for the font family being used.  [Oswald](https://fonts.google.com/specimen/Oswald) bold is 700 which is being inherited from the @include theme-card-header.  I would just remove the font-weight override.

2021-07-29 13:23 UTC, Shinsina commented
> For clarity, can you provide before and after screen shots and update your first PR comment to show them (as opposed to adding new comments).

Comment updated

2021-07-29 15:08 UTC, zarathustra323 approved these changes

2021-07-29 15:08 UTC, merged