Update font weight on published content page cards
parameter1/bizbash-media-websites pull request #55
Opened 2021-07-30 15:24 UTC by Shinsina

This also has a fix for the gather geeks page not filling the load more section out fully

BEFORE: 
<img width="1920" alt="Screen Shot 2021-07-30 at 9 31 24 AM" src="https://user-images.githubusercontent.com/46794001/127668718-67d0a696-f040-4cdc-a3d9-f81a59fa0dca.png">
<img width="1917" alt="Screen Shot 2021-07-30 at 9 31 36 AM" src="https://user-images.githubusercontent.com/46794001/127668729-7919729d-41ed-4cfa-8bdb-289856b7c531.png">
<img width="1920" alt="Screen Shot 2021-07-30 at 9 31 44 AM" src="https://user-images.githubusercontent.com/46794001/127668736-d3e88d9b-a46c-48aa-9b7e-bf1a5a057f76.png">
<img width="1920" alt="Screen Shot 2021-07-30 at 9 31 53 AM" src="https://user-images.githubusercontent.com/46794001/127668742-14d2e3d3-b963-4e1f-83e8-4132f7e892ab.png">
<img width="1920" alt="Screen Shot 2021-07-30 at 9 32 17 AM" src="https://user-images.githubusercontent.com/46794001/127668744-7bffec8f-9cb3-4ec0-b4e9-e0dc78944514.png">

AFTER:
<img width="1920" alt="Screen Shot 2021-07-30 at 9 32 35 AM" src="https://user-images.githubusercontent.com/46794001/127668771-f24d53c3-9184-44dd-947e-8f784e0e870e.png">
<img width="1920" alt="Screen Shot 2021-07-30 at 9 32 43 AM" src="https://user-images.githubusercontent.com/46794001/127668776-6d6eb7f6-b542-4621-b108-bb9307f46e7e.png">
<img width="1920" alt="Screen Shot 2021-07-30 at 9 32 52 AM" src="https://user-images.githubusercontent.com/46794001/127668781-0d8a784b-f9f3-4746-a43a-a34a7b1ac3ef.png">
<img width="1920" alt="Screen Shot 2021-07-30 at 9 32 58 AM" src="https://user-images.githubusercontent.com/46794001/127668873-287e6dfe-e376-44be-a0d2-6038e7c17a77.png">
<img width="1920" alt="Screen Shot 2021-07-30 at 9 33 09 AM" src="https://user-images.githubusercontent.com/46794001/127668885-8d3720d8-1e29-457f-bde0-67c57bd1c18d.png">

2021-07-30 15:24 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [MEDIUM URGENCY: Switch Webinars, White Papers and Podcast landing pages back to original design.](https://trello.com/c/M4QSPL6j/77-medium-urgency-switch-webinars-white-papers-and-podcast-landing-pages-back-to-original-design)

2021-07-30 15:45 UTC, zarathustra323 requested changes

2021-07-30 15:45 UTC, zarathustra323 commented on packages/global/scss/index.scss
> +        &--published {
Semantically it would be better for the modifier to describe what's being modified. In this case bold would be preferred over published.

2021-08-01 13:19 UTC, zarathustra323 requested changes

2021-08-01 13:19 UTC, zarathustra323 commented on packages/global/scss/index.scss
> +    .node {
Just noticed this... the nested .node shouldn't be needed

2021-08-02 13:39 UTC, zarathustra323 approved these changes

2021-08-02 13:39 UTC, merged